codeigniter4/devkit

src/.github/workflows/rector.yml
src/rector.php

Per https://github.com/codeigniter4/CodeIgniter4/pull/5523#issuecomment-1003720752

[Rector] Set parallel config

---

src/Template/rector.php

Adds the option to tell Rector which PHPStan configuration to use.

Rector PHPStan

---

README.md
composer.json
src/Template/.github/workflows/rector.yml
src/Template/rector.php

@MGatner this is to update not only private method, but also protected and public when possible.

[Rector] Enable TypedPropertyRector::INLINE_PUBLIC

---

src/Template/.github/workflows/unused.yml

fix: remove --profile of composer-unused

---

src/docker/README.md
src/docker/docker-compose.yaml

- PostgreSQL 13
- SQL Server 2019
- MySQL 5.7

feat: add docker-compose.yaml for databases

---

src/Template/.github/workflows/deptrac.yml
src/Template/.github/workflows/infection.yml
src/Template/.github/workflows/phpstan.yml
src/Template/.github/workflows/phpunit.yml
src/Template/.github/workflows/rector.yml
src/Template/.github/workflows/unused.yml

> The ** wildcard matches any character including slash (/). 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

fix: github workflows paths

---

src/Template/.github/workflows/deptrac.yml
src/Template/.github/workflows/infection.yml
src/Template/.github/workflows/phpcpd.yml
src/Template/.github/workflows/phpcsfixer.yml
src/Template/.github/workflows/phpstan.yml
src/Template/.github/workflows/phpunit.yml
src/Template/.github/workflows/rector.yml
src/Template/.github/workflows/unused.yml

Updates Template workflows to use `v3` of GitHub Checkout.

GitHub Checkout v3

---

src/Template/.github/workflows/deptrac.yml
src/Template/.github/workflows/infection.yml
src/Template/.github/workflows/phpcsfixer.yml
src/Template/.github/workflows/phpstan.yml
src/Template/.github/workflows/phpunit.yml
src/Template/.github/workflows/rector.yml
src/Template/.github/workflows/unused.yml

Updates the cache action version to 3 in all templates.

Cache Action v3

---

src/Template/rector.php

ref https://getrector.org/blog/new-in-rector-012-introducing-rector-config-with-autocomplete

Update to new RectorConfig

---

src/Template/rector.php

See https://github.com/codeigniter4/devkit/pull/12#discussion_r863675910

docs: add comment for TypedPropertyRector

---

composer.json
src/Template/.github/workflows/deptrac.yml
src/Template/.github/workflows/infection.yml
src/Template/.github/workflows/phpcpd.yml
src/Template/.github/workflows/phpcsfixer.yml
src/Template/.github/workflows/psalm.yml
src/Template/.github/workflows/unused.yml
src/Template/deptrac.yaml

A few housekeeping tasks.
Fixes #31

chore: Housekeeping

---

composer.json

Scripts from https://github.com/codeigniter4/CodeIgniter4 and https://github.com/codeigniter4/shield

Add composer scripts

---

src/Template/rector.php

Updates the set list version to match the PHPUnit config.

Rector: PHPUnit Version

---

psalm_autoload.php
src/Template/psalm_autoload.php

`baseline.xml` was created in `system/Helpers/`.

fix: psalm_autoload.php

---

composer.json

See https://github.com/codeigniter4/CodeIgniter4/pull/6931

chore: update psalm to ^5.0

---

README.md

docs: fix installation commands

---

src/Template/phpstan.neon.dist

See https://github.com/codeigniter4/CodeIgniter4/pull/7713

Bump phpstan level to 6

---

composer.json

Followup codeigniter4/CodeIgniter4#7715

chore: `disableProcessTimeout` in `analyze` script

---

src/Template/.github/workflows/deptrac.yml
src/Template/.github/workflows/infection.yml
src/Template/.github/workflows/phpcpd.yml
src/Template/.github/workflows/phpcsfixer.yml
src/Template/.github/workflows/phpstan.yml
src/Template/.github/workflows/phpunit.yml
src/Template/.github/workflows/psalm.yml
src/Template/.github/workflows/rector.yml
src/Template/.github/workflows/unused.yml

chore: update actions/checkout version to v4

---

src/docker/README.md
src/docker/docker-compose.yaml

**Description**
- update docker MySQL version
**Checklist:**

Update docker MySQL to 8.0
